package com.example.scubadivetracker.model.Dive

import androidx.room.Entity
import androidx.room.PrimaryKey
/**
 * Represents a single scuba dive entry in the local Room database.
 *
 * Each dive record stores essential details such as location, depth, duration,
 * date, and additional notes. The class is annotated with [Entity] so that
 * Room can automatically generate and manage the corresponding database table.
 *
 * @property id Unique identifier for the dive entry. This value is
 * automatically generated by Room when a new dive is inserted.
 * @property location The name or description of the dive location.
 * @property depth The depth of the dive in feet.
 * @property duration The duration of the dive in minutes.
 * @property date The date of the dive in string format (e.g., "2025-10-07").
 * @property notes Optional notes or observations made during the dive.
 */
@Entity(tableName = "dive_table")
data class Dive(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val location: String,
    val depth: Double,
    val duration: Int,
    val date: String,
    val notes: String
)
